sudo: required
env:
  global:
    - MINIO_VER="RELEASE.2019-09-26T19-42-35Z"
    - ALPINE_VER="3.10"
    - COMPOSE_HTTP_TIMEOUT="300"
    - UID="2000"
    - GID="2000"
    - COVERALLS_SERVICE_NAME="travis-ci"
    - COVERALLS_REPO_TOKEN="fd0BoXG46TPReEem0uMy7BJO5j0w1MQiY"
services: 
- docker
main: &main
      stage: Alpine
      os: linux
      dist: xenial # precise, trusty, xenial, bionic
      language: shell
      script:
        - docker-compose -f LNX-docker-compose.yml up --build --exit-code-from app
jobs:
  include:
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.7"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.6"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.5"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "8.0"
    - <<: *main
      env:
      - PY_VER: "3.7"
      - MYSQL_VER: "8.0"
    - <<: *main
      env:
      - PY_VER: "3.6"
      - MYSQL_VER: "8.0"
    - <<: *main
      env:
      - PY_VER: "3.5"
      - MYSQL_VER: "8.0"
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "5.6"
    - <<: *main
      env:
      - PY_VER: "3.7"
      - MYSQL_VER: "5.6"
    - <<: *main
      env:
      - PY_VER: "3.6"
      - MYSQL_VER: "5.6"
    - <<: *main
      env:
      - PY_VER: "3.5"
      - MYSQL_VER: "5.6"
